#############################################################################
# Makefile for building: prointegra-OPC
# Generated by qmake (2.01a) (Qt 4.8.7) on: vie dic 9 13:15:30 2016
# Project:  prointegra-OPC.pro
# Template: app
# Command: /usr/lib64/qt4/bin/qmake -o Makefile prointegra-OPC.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/opt/pvb/pvserver -I/opt/pvb/rllib/lib -Ilib/gStools -Ilib/pugixml-1.7/src -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 /usr/lib/libpvsmt.so /usr/lib/librllib.so -L./lib/gStools -lgStools -lQtSql -L/usr/lib64/qt4 -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib64/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		prointegraOPC.cpp \
		qtdatabase.cpp \
		commDaemon.cpp \
		dataManaging.cpp \
		piDatabase.cpp \
		piComm.cpp \
		iniConfigurator.cpp \
		config.cpp \
		lib/pugixml-1.7/src/pugixml.cpp 
OBJECTS       = main.o \
		prointegraOPC.o \
		qtdatabase.o \
		commDaemon.o \
		dataManaging.o \
		piDatabase.o \
		piComm.o \
		iniConfigurator.o \
		config.o \
		pugixml.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		prointegra-OPC.pro
QMAKE_TARGET  = prointegra-OPC
DESTDIR       = 
TARGET        = prointegra-OPC

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: prointegra-OPC.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/qt4/libQtSql.prl \
		/usr/lib64/qt4/libQtCore.prl \
		/usr/lib64/qt4/libQtGui.prl
	$(QMAKE) -o Makefile prointegra-OPC.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/qt4/libQtSql.prl:
/usr/lib64/qt4/libQtCore.prl:
/usr/lib64/qt4/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile prointegra-OPC.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/prointegra-OPC1.0.0 || $(MKDIR) .tmp/prointegra-OPC1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/prointegra-OPC1.0.0/ && $(COPY_FILE) --parents pvapp.h prointegraOPC.h qtdatabase.h commDaemon.h dataManaging.h piDatabase.h piComm.h iniConfigurator.h config.h lib/pugixml-1.7/src/pugixml.hpp lib/pugixml-1.7/src/pugiconfig.hpp .tmp/prointegra-OPC1.0.0/ && $(COPY_FILE) --parents main.cpp prointegraOPC.cpp qtdatabase.cpp commDaemon.cpp dataManaging.cpp piDatabase.cpp piComm.cpp iniConfigurator.cpp config.cpp lib/pugixml-1.7/src/pugixml.cpp .tmp/prointegra-OPC1.0.0/ && (cd `dirname .tmp/prointegra-OPC1.0.0` && $(TAR) prointegra-OPC1.0.0.tar prointegra-OPC1.0.0 && $(COMPRESS) prointegra-OPC1.0.0.tar) && $(MOVE) `dirname .tmp/prointegra-OPC1.0.0`/prointegra-OPC1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/prointegra-OPC1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp pvapp.h \
		prointegraOPC.h \
		piDatabase.h \
		qtdatabase.h \
		config.h \
		piComm.h \
		iniConfigurator.h \
		lib/gStools/libgStools.h \
		lib/gStools/gStDate.h \
		lib/gStools/gStMisc.h \
		lib/gStools/gStConv.h \
		dataManaging.h \
		commDaemon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

prointegraOPC.o: prointegraOPC.cpp prointegraOPC.h \
		piDatabase.h \
		qtdatabase.h \
		config.h \
		piComm.h \
		iniConfigurator.h \
		lib/gStools/libgStools.h \
		lib/gStools/gStDate.h \
		lib/gStools/gStMisc.h \
		lib/gStools/gStConv.h \
		dataManaging.h \
		commDaemon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prointegraOPC.o prointegraOPC.cpp

qtdatabase.o: qtdatabase.cpp qtdatabase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtdatabase.o qtdatabase.cpp

commDaemon.o: commDaemon.cpp commDaemon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commDaemon.o commDaemon.cpp

dataManaging.o: dataManaging.cpp dataManaging.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataManaging.o dataManaging.cpp

piDatabase.o: piDatabase.cpp piDatabase.h \
		qtdatabase.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o piDatabase.o piDatabase.cpp

piComm.o: piComm.cpp piComm.h \
		config.h \
		iniConfigurator.h \
		lib/gStools/libgStools.h \
		lib/gStools/gStDate.h \
		lib/gStools/gStMisc.h \
		lib/gStools/gStConv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o piComm.o piComm.cpp

iniConfigurator.o: iniConfigurator.cpp iniConfigurator.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o iniConfigurator.o iniConfigurator.cpp

config.o: config.cpp config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o config.cpp

pugixml.o: lib/pugixml-1.7/src/pugixml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pugixml.o lib/pugixml-1.7/src/pugixml.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

